name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    

    
    - name: Restore .NET dependencies
      run: dotnet restore Portfolio.csproj
    
    - name: Copy Azure configuration
      run: |
        cp appsettings.Azure.json appsettings.json
    
    - name: Ensure wwwroot exists
      run: |
        mkdir -p wwwroot
        echo "wwwroot directory created/verified"
    
    - name: List wwwroot contents
      run: |
        ls -la wwwroot/
        echo "--- CSS directory ---"
        ls -la wwwroot/css/ || echo "CSS directory not found"
        echo "--- LIB directory ---"
        ls -la wwwroot/lib/ || echo "LIB directory not found"
    
    - name: Build .NET app
      run: dotnet build Portfolio.csproj --no-restore --configuration Release
    
    - name: Publish .NET app
      run: dotnet publish Portfolio.csproj --no-build --configuration Release --output ./publish
    
    - name: Copy wwwroot to publish output
      run: |
        cp -r wwwroot/* ./publish/wwwroot/ || echo "wwwroot copy failed"
        echo "--- Publish wwwroot contents ---"
        ls -la ./publish/wwwroot/ || echo "Publish wwwroot not found"
    
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'YOUR_APP_SERVICE_NAME'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish
    
 