using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Portfolio.Migrations
{
    /// <inheritdoc />
    public partial class InitialMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Add Role column to Admins table if it doesn't exist
            migrationBuilder.Sql(@"
                DO $$ 
                BEGIN 
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='Admins' AND column_name='Role') THEN
                        ALTER TABLE ""Admins"" ADD ""Role"" character varying(20) NOT NULL DEFAULT 'Admin';
                    END IF;
                END $$;
            ");

            // Create missing tables only if they don't exist
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""HomePages"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""HeaderTitle"" character varying(100) NOT NULL,
                    ""HeaderSubtitle"" character varying(500) NOT NULL,
                    ""HeaderDescription"" character varying(1000),
                    ""HeaderBackgroundImageUrl"" character varying(500),
                    ""HeaderBackgroundVideoUrl"" character varying(500),
                    ""HeaderBackgroundStyle"" character varying(500),
                    ""HeaderPrimaryButtonText"" character varying(50),
                    ""HeaderPrimaryButtonUrl"" character varying(200),
                    ""HeaderSecondaryButtonText"" character varying(50),
                    ""HeaderSecondaryButtonUrl"" character varying(200),
                    ""ShowHeaderPrimaryButton"" boolean NOT NULL DEFAULT true,
                    ""ShowHeaderSecondaryButton"" boolean NOT NULL DEFAULT true,
                    ""HeaderOverlayColor"" character varying(50),
                    ""HeaderOverlayOpacity"" real,
                    ""HeaderTextColor"" character varying(50),
                    ""HeaderButtonColor"" character varying(50),
                    ""HeaderButtonTextColor"" character varying(50),
                    ""SkillsSectionTitle"" character varying(100),
                    ""SkillsSectionSubtitle"" character varying(500),
                    ""SkillsCategoriesJson"" jsonb NOT NULL DEFAULT '[]',
                    ""FeaturedProjectsTitle"" character varying(100),
                    ""FeaturedProjectsSubtitle"" character varying(500),
                    ""FeaturedProjectsJson"" jsonb NOT NULL DEFAULT '[]',
                    ""CTATitle"" character varying(100),
                    ""CTASubtitle"" character varying(500),
                    ""CTAButtonText"" character varying(50),
                    ""CTAButtonUrl"" character varying(200),
                    ""CTABackgroundImageUrl"" character varying(500),
                    ""CTATextColor"" character varying(50),
                    ""DisplayOrder"" integer NOT NULL DEFAULT 0,
                    ""IsActive"" boolean NOT NULL DEFAULT true,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                    ""UpdatedAt"" timestamp with time zone,
                    CONSTRAINT ""PK_HomePages"" PRIMARY KEY (""Id"")
                );
                
                CREATE TABLE IF NOT EXISTS ""Projects"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Title"" text NOT NULL,
                    ""Description"" text NOT NULL,
                    ""ImageUrl"" text NOT NULL,
                    ""ProjectUrl"" text NOT NULL,
                    ""GitHubUrl"" text NOT NULL,
                    ""TechnologiesJson"" jsonb NOT NULL DEFAULT '[]',
                    ""CompletionDate"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_Projects"" PRIMARY KEY (""Id"")
                );
                
                CREATE TABLE IF NOT EXISTS ""SkillsCategories"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" character varying(100) NOT NULL,
                    ""Description"" character varying(500) NOT NULL DEFAULT '',
                    ""ImagePath"" text NOT NULL DEFAULT '',
                    ""SkillsJson"" jsonb NOT NULL DEFAULT '[]',
                    ""DisplayOrder"" integer NOT NULL DEFAULT 0,
                    ""IsActive"" boolean NOT NULL DEFAULT true,
                    CONSTRAINT ""PK_SkillsCategories"" PRIMARY KEY (""Id"")
                );
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Remove Role column from Admins table
            migrationBuilder.DropColumn(
                name: "Role",
                table: "Admins");
        }
    }
}