name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Restore .NET dependencies
      run: dotnet restore Portfolio.csproj
    
    - name: Install Node.js dependencies
      run: |
        cd ClientApp
        npm cache clean --force
        npm install --no-audit --no-fund --legacy-peer-deps
    
    - name: Build React app
      run: |
        cd ClientApp
        npm run build
    
    - name: Copy React build to wwwroot
      run: |
        mkdir -p wwwroot
        cp -r ClientApp/build/* wwwroot/
    
    - name: Build .NET app
      run: dotnet build Portfolio.csproj --no-restore --configuration Release
    
    - name: Publish .NET app
      run: dotnet publish Portfolio.csproj --no-build --configuration Release --output ./publish
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_16CAD5F1BD9C46EDB5AC1D29ECFF4811 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E7E2D612BC2D44D8B524E20CED405F89 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FC9A748DF011496D92EB0CAF79CE0A80 }}
    
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'portfolio-app-1776'
        package: ./publish 