name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ClientApp/package-lock.json
        registry-url: 'https://registry.npmjs.org'
    
    - name: Update npm to latest version
      run: npm install -g npm@latest
    
    - name: Restore .NET dependencies
      run: dotnet restore
    
    - name: Install Node.js dependencies
      run: |
        export WEBSITE_NODE_DEFAULT_VERSION=18.19.0
        npm cache clean --force
        npm config set registry https://registry.npmjs.org/
        timeout 600 npm install --prefix ClientApp --no-audit --no-fund || (echo "npm install timed out, retrying..." && timeout 600 npm install --prefix ClientApp --no-audit --no-fund)
    
    - name: Build React app
      run: npm run build --prefix ClientApp
    
    - name: Copy React build to wwwroot
      run: |
        mkdir -p wwwroot
        cp -r ClientApp/build/* wwwroot/
    
    - name: Build .NET app
      run: dotnet build --no-restore --configuration Release
    
    - name: Publish .NET app
      run: dotnet publish --no-build --configuration Release --output ./publish
    
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'portfolio-app-1776'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish 