name: Deploy Frontend to Azure App Service

on:
  push:
    branches: [ main ]
    paths:
      - 'ClientApp/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ClientApp/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd ClientApp
        ls -la
        npm install
    
    - name: Build React app
      run: |
        cd ClientApp
        npm run build
      env:
        REACT_APP_API_URL: https://portfolio-app-1776-hkdfazazd5cqfzbk.centralus-01.azurewebsites.net/api
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_16CAD5F1BD9C46EDB5AC1D29ECFF4811 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E7E2D612BC2D44D8B524E20CED405F89 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FC9A748DF011496D92EB0CAF79CE0A80 }}
    
    - name: Set Azure context
      run: |
        az webapp list --resource-group portfolio-frontend --query "[].name" -o tsv
        az webapp show --name portfolio-frontend-1776 --resource-group portfolio-frontend
    
    - name: Configure App Service for static files
      run: |
        az webapp config set --name portfolio-frontend-1776 --resource-group portfolio-frontend --startup-file "pm2 serve /home/site/wwwroot --no-daemon --spa"
    
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'portfolio-frontend-1776'
        package: ClientApp/build
        resource-group-name: 'portfolio-frontend'
    
    - name: Check deployed files
      run: |
        az webapp deployment list --name portfolio-frontend-1776 --resource-group portfolio-frontend
        az webapp browse --name portfolio-frontend-1776 --resource-group portfolio-frontend 